// Curated worldwide city list keyed by the canonical country display names
// used in COUNTRIES (public reference data). Used by the New Search city
// picker: selecting a country filters the searchable city dropdown to that
// country's major cities. Not exhaustive — covers capitals + major metros —
// but the picker still accepts any free-text city the user types.

export const CITIES_BY_COUNTRY: Record<string, string[]> = {
  'Afghanistan': ['Kabul', 'Kandahar', 'Herat', 'Mazar-i-Sharif', 'Jalalabad', 'Kunduz'],
  'Albania': ['Tirana', 'Durrës', 'Vlorë', 'Shkodër', 'Elbasan', 'Fier', 'Korçë'],
  'Algeria': ['Algiers', 'Oran', 'Constantine', 'Annaba', 'Blida', 'Batna', 'Sétif', 'Sidi Bel Abbès'],
  'Andorra': ['Andorra la Vella', 'Escaldes-Engordany', 'Encamp', 'La Massana'],
  'Angola': ['Luanda', 'Lobito', 'Benguela', 'Huambo', 'Cabinda', 'Lubango'],
  'Antigua and Barbuda': ['St. John\'s', 'All Saints', 'Liberta'],
  'Argentina': ['Buenos Aires', 'Córdoba', 'Rosario', 'Mendoza', 'La Plata', 'Mar del Plata', 'Salta', 'San Miguel de Tucumán', 'Santa Fe'],
  'Armenia': ['Yerevan', 'Gyumri', 'Vanadzor', 'Vagharshapat'],
  'Australia': ['Sydney', 'Melbourne', 'Brisbane', 'Perth', 'Adelaide', 'Gold Coast', 'Canberra', 'Newcastle', 'Hobart', 'Darwin', 'Geelong', 'Sunshine Coast', 'Wollongong'],
  'Austria': ['Vienna', 'Graz', 'Linz', 'Salzburg', 'Innsbruck', 'Klagenfurt'],
  'Azerbaijan': ['Baku', 'Ganja', 'Sumqayit', 'Mingachevir', 'Lankaran'],
  'Bahamas': ['Nassau', 'Freeport', 'Marsh Harbour'],
  'Bahrain': ['Manama', 'Riffa', 'Muharraq', 'Hamad Town'],
  'Bangladesh': ['Dhaka', 'Chittagong', 'Khulna', 'Rajshahi', 'Sylhet', 'Barisal', 'Rangpur', 'Cumilla'],
  'Barbados': ['Bridgetown', 'Speightstown', 'Oistins'],
  'Belarus': ['Minsk', 'Gomel', 'Mogilev', 'Vitebsk', 'Grodno', 'Brest'],
  'Belgium': ['Brussels', 'Antwerp', 'Ghent', 'Charleroi', 'Liège', 'Bruges', 'Namur'],
  'Belize': ['Belize City', 'Belmopan', 'San Ignacio', 'Orange Walk'],
  'Benin': ['Porto-Novo', 'Cotonou', 'Parakou', 'Djougou'],
  'Bhutan': ['Thimphu', 'Phuntsholing', 'Paro', 'Punakha'],
  'Bolivia': ['La Paz', 'Santa Cruz de la Sierra', 'Cochabamba', 'Sucre', 'El Alto', 'Oruro'],
  'Bosnia and Herzegovina': ['Sarajevo', 'Banja Luka', 'Tuzla', 'Mostar', 'Zenica'],
  'Botswana': ['Gaborone', 'Francistown', 'Maun', 'Molepolole'],
  'Brazil': ['São Paulo', 'Rio de Janeiro', 'Brasília', 'Salvador', 'Fortaleza', 'Belo Horizonte', 'Manaus', 'Curitiba', 'Recife', 'Porto Alegre', 'Belém', 'Goiânia', 'Campinas'],
  'Brunei': ['Bandar Seri Begawan', 'Kuala Belait', 'Seria'],
  'Bulgaria': ['Sofia', 'Plovdiv', 'Varna', 'Burgas', 'Ruse', 'Stara Zagora'],
  'Burkina Faso': ['Ouagadougou', 'Bobo-Dioulasso', 'Koudougou', 'Ouahigouya'],
  'Burundi': ['Bujumbura', 'Gitega', 'Muyinga'],
  'Cabo Verde': ['Praia', 'Mindelo', 'Santa Maria'],
  'Cambodia': ['Phnom Penh', 'Siem Reap', 'Battambang', 'Sihanoukville'],
  'Cameroon': ['Yaoundé', 'Douala', 'Bamenda', 'Bafoussam', 'Garoua'],
  'Canada': ['Toronto', 'Montreal', 'Vancouver', 'Calgary', 'Edmonton', 'Ottawa', 'Winnipeg', 'Quebec City', 'Hamilton', 'Kitchener', 'London', 'Halifax', 'Victoria', 'Saskatoon', 'Regina', 'St. John\'s', 'Moncton', 'Kelowna', 'Windsor'],
  'Central African Republic': ['Bangui', 'Bimbo', 'Berbérati'],
  'Chad': ["N'Djamena", 'Moundou', 'Sarh', 'Abéché'],
  'Chile': ['Santiago', 'Valparaíso', 'Concepción', 'La Serena', 'Antofagasta', 'Temuco', 'Rancagua'],
  'China': ['Beijing', 'Shanghai', 'Guangzhou', 'Shenzhen', 'Chengdu', 'Wuhan', 'Xi\'an', 'Hangzhou', 'Nanjing', 'Chongqing', 'Tianjin', 'Suzhou', 'Harbin', 'Qingdao', 'Dalian'],
  'Colombia': ['Bogotá', 'Medellín', 'Cali', 'Barranquilla', 'Cartagena', 'Bucaramanga', 'Pereira', 'Cúcuta'],
  'Comoros': ['Moroni', 'Mutsamudu', 'Fomboni'],
  'Congo': ['Brazzaville', 'Pointe-Noire', 'Dolisie'],
  'Democratic Republic of the Congo': ['Kinshasa', 'Lubumbashi', 'Mbuji-Mayi', 'Kisangani', 'Kananga', 'Goma', 'Bukavu'],
  'Costa Rica': ['San José', 'Alajuela', 'Cartago', 'Heredia', 'Liberia'],
  'Croatia': ['Zagreb', 'Split', 'Rijeka', 'Osijek', 'Zadar', 'Dubrovnik', 'Pula'],
  'Cuba': ['Havana', 'Santiago de Cuba', 'Camagüey', 'Holguín', 'Santa Clara'],
  'Cyprus': ['Nicosia', 'Limassol', 'Larnaca', 'Famagusta', 'Paphos'],
  'Czech Republic': ['Prague', 'Brno', 'Ostrava', 'Plzeň', 'Liberec', 'Olomouc'],
  'Denmark': ['Copenhagen', 'Aarhus', 'Odense', 'Aalborg', 'Esbjerg'],
  'Djibouti': ['Djibouti City', 'Ali Sabieh', 'Tadjoura'],
  'Dominica': ['Roseau', 'Portsmouth', 'Marigot'],
  'Dominican Republic': ['Santo Domingo', 'Santiago de los Caballeros', 'La Romana', 'San Pedro de Macorís', 'Puerto Plata'],
  'Ecuador': ['Quito', 'Guayaquil', 'Cuenca', 'Santo Domingo', 'Machala', 'Manta'],
  'Egypt': ['Cairo', 'Alexandria', 'Giza', 'Shubra El Kheima', 'Port Said', 'Suez', 'Luxor', 'Aswan', 'Mansoura'],
  'El Salvador': ['San Salvador', 'Santa Ana', 'San Miguel', 'Santa Tecla'],
  'Equatorial Guinea': ['Malabo', 'Bata', 'Ebebiyín'],
  'Eritrea': ['Asmara', 'Keren', 'Massawa'],
  'Estonia': ['Tallinn', 'Tartu', 'Narva', 'Pärnu'],
  'Eswatini': ['Mbabane', 'Manzini', 'Lobamba'],
  'Ethiopia': ['Addis Ababa', 'Dire Dawa', 'Mekelle', 'Gondar', 'Bahir Dar', 'Hawassa', 'Adama'],
  'Fiji': ['Suva', 'Nadi', 'Lautoka', 'Ba'],
  'Finland': ['Helsinki', 'Espoo', 'Tampere', 'Vantaa', 'Oulu', 'Turku', 'Jyväskylä'],
  'France': ['Paris', 'Marseille', 'Lyon', 'Toulouse', 'Nice', 'Nantes', 'Strasbourg', 'Montpellier', 'Bordeaux', 'Lille', 'Rennes', 'Grenoble'],
  'Gabon': ['Libreville', 'Port-Gentil', 'Franceville', 'Oyem'],
  'Gambia': ['Banjul', 'Serekunda', 'Brikama'],
  'Georgia': ['Tbilisi', 'Batumi', 'Kutaisi', 'Rustavi', 'Zugdidi'],
  'Germany': ['Berlin', 'Hamburg', 'Munich', 'Cologne', 'Frankfurt', 'Stuttgart', 'Düsseldorf', 'Dortmund', 'Essen', 'Leipzig', 'Bremen', 'Dresden', 'Hannover', 'Nuremberg'],
  'Ghana': ['Accra', 'Kumasi', 'Tamale', 'Takoradi', 'Cape Coast', 'Tema'],
  'Greece': ['Athens', 'Thessaloniki', 'Patras', 'Heraklion', 'Larissa', 'Volos'],
  'Grenada': ["St. George's", 'Grenville', 'Gouyave'],
  'Guatemala': ['Guatemala City', 'Mixco', 'Villa Nueva', 'Quetzaltenango', 'Escuintla'],
  'Guinea': ['Conakry', 'Nzérékoré', 'Kankan', 'Kindia'],
  'Guinea-Bissau': ['Bissau', 'Bafatá', 'Gabú'],
  'Guyana': ['Georgetown', 'Linden', 'New Amsterdam'],
  'Haiti': ['Port-au-Prince', 'Cap-Haïtien', 'Gonaïves', 'Les Cayes'],
  'Honduras': ['Tegucigalpa', 'San Pedro Sula', 'La Ceiba', 'Choloma'],
  'Hong Kong': ['Central', 'Tsim Sha Tsui', 'Mong Kok', 'Causeway Bay', 'Wan Chai', 'Kwun Tong', 'Sha Tin', 'Tuen Mun'],
  'Hungary': ['Budapest', 'Debrecen', 'Szeged', 'Miskolc', 'Pécs', 'Győr'],
  'Iceland': ['Reykjavík', 'Kópavogur', 'Akureyri', 'Reykjanesbær'],
  'India': ['Mumbai', 'Delhi', 'Bengaluru', 'Hyderabad', 'Chennai', 'Kolkata', 'Pune', 'Ahmedabad', 'Jaipur', 'Surat', 'Lucknow', 'Kanpur', 'Nagpur', 'Indore', 'Thane', 'Bhopal', 'Visakhapatnam', 'Vadodara'],
  'Indonesia': ['Jakarta', 'Surabaya', 'Bandung', 'Medan', 'Semarang', 'Makassar', 'Palembang', 'Denpasar', 'Yogyakarta'],
  'Iran': ['Tehran', 'Mashhad', 'Isfahan', 'Karaj', 'Shiraz', 'Tabriz', 'Qom', 'Ahvaz'],
  'Iraq': ['Baghdad', 'Basra', 'Mosul', 'Erbil', 'Najaf', 'Karbala', 'Sulaymaniyah'],
  'Ireland': ['Dublin', 'Cork', 'Limerick', 'Galway', 'Waterford', 'Drogheda'],
  'Israel': ['Jerusalem', 'Tel Aviv', 'Haifa', 'Rishon LeZion', 'Petah Tikva', 'Netanya', 'Beersheba'],
  'Italy': ['Rome', 'Milan', 'Naples', 'Turin', 'Palermo', 'Genoa', 'Bologna', 'Florence', 'Venice', 'Verona', 'Bari', 'Catania'],
  'Ivory Coast': ['Abidjan', 'Yamoussoukro', 'Bouaké', 'Daloa', 'San-Pédro'],
  'Jamaica': ['Kingston', 'Montego Bay', 'Spanish Town', 'Portmore'],
  'Japan': ['Tokyo', 'Yokohama', 'Osaka', 'Nagoya', 'Sapporo', 'Fukuoka', 'Kobe', 'Kyoto', 'Kawasaki', 'Hiroshima', 'Sendai'],
  'Jordan': ['Amman', 'Zarqa', 'Irbid', 'Aqaba', 'Madaba'],
  'Kazakhstan': ['Almaty', 'Astana', 'Shymkent', 'Karaganda', 'Aktobe', 'Pavlodar'],
  'Kenya': ['Nairobi', 'Mombasa', 'Kisumu', 'Nakuru', 'Eldoret', 'Thika'],
  'Kiribati': ['Tarawa', 'Betio', 'Bikenibeu'],
  'Kuwait': ['Kuwait City', 'Salmiya', 'Hawalli', 'Al Ahmadi'],
  'Kyrgyzstan': ['Bishkek', 'Osh', 'Jalal-Abad', 'Karakol'],
  'Laos': ['Vientiane', 'Pakse', 'Savannakhet', 'Luang Prabang'],
  'Latvia': ['Riga', 'Daugavpils', 'Liepāja', 'Jelgava', 'Ventspils'],
  'Lebanon': ['Beirut', 'Tripoli', 'Sidon', 'Tyre', 'Jounieh'],
  'Lesotho': ['Maseru', 'Teyateyaneng', 'Mafeteng'],
  'Liberia': ['Monrovia', 'Gbarnga', 'Kakata', 'Buchanan'],
  'Libya': ['Tripoli', 'Benghazi', 'Misrata', 'Zawiya', 'Sabha'],
  'Liechtenstein': ['Vaduz', 'Schaan', 'Balzers'],
  'Lithuania': ['Vilnius', 'Kaunas', 'Klaipėda', 'Šiauliai', 'Panevėžys'],
  'Luxembourg': ['Luxembourg City', 'Esch-sur-Alzette', 'Differdange'],
  'Macau': ['Macau', 'Taipa', 'Cotai'],
  'Madagascar': ['Antananarivo', 'Toamasina', 'Antsirabe', 'Mahajanga', 'Fianarantsoa'],
  'Malawi': ['Lilongwe', 'Blantyre', 'Mzuzu', 'Zomba'],
  'Malaysia': ['Kuala Lumpur', 'George Town', 'Johor Bahru', 'Ipoh', 'Shah Alam', 'Malacca City', 'Kota Kinabalu', 'Kuching'],
  'Maldives': ['Malé', 'Addu City', 'Fuvahmulah'],
  'Mali': ['Bamako', 'Sikasso', 'Mopti', 'Koutiala', 'Segou'],
  'Malta': ['Valletta', 'Birkirkara', 'Mosta', 'Sliema', 'Qormi'],
  'Marshall Islands': ['Majuro', 'Ebeye', 'Jaluit'],
  'Mauritania': ['Nouakchott', 'Nouadhibou', 'Kiffa', 'Rosso'],
  'Mauritius': ['Port Louis', 'Beau Bassin-Rose Hill', 'Curepipe', 'Vacoas'],
  'Mexico': ['Mexico City', 'Guadalajara', 'Monterrey', 'Puebla', 'Tijuana', 'León', 'Ciudad Juárez', 'Cancún', 'Mérida', 'Querétaro', 'San Luis Potosí', 'Toluca', 'Veracruz'],
  'Micronesia': ['Palikir', 'Weno', 'Kolonia'],
  'Moldova': ['Chișinău', 'Tiraspol', 'Bălți', 'Bender'],
  'Monaco': ['Monaco', 'Monte Carlo', 'La Condamine'],
  'Mongolia': ['Ulaanbaatar', 'Erdenet', 'Darkhan', 'Choibalsan'],
  'Montenegro': ['Podgorica', 'Nikšić', 'Herceg Novi', 'Bar'],
  'Morocco': ['Casablanca', 'Rabat', 'Marrakesh', 'Fez', 'Tangier', 'Agadir', 'Meknes', 'Oujda'],
  'Mozambique': ['Maputo', 'Matola', 'Beira', 'Nampula', 'Chimoio'],
  'Myanmar': ['Yangon', 'Mandalay', 'Naypyidaw', 'Bago', 'Mawlamyine'],
  'Namibia': ['Windhoek', 'Walvis Bay', 'Swakopmund', 'Rundu'],
  'Nauru': ['Yaren', 'Denigomodu', 'Aiwo'],
  'Nepal': ['Kathmandu', 'Pokhara', 'Lalitpur', 'Biratnagar', 'Birgunj', 'Bharatpur'],
  'Netherlands': ['Amsterdam', 'Rotterdam', 'The Hague', 'Utrecht', 'Eindhoven', 'Groningen', 'Tilburg', 'Almere'],
  'New Zealand': ['Auckland', 'Wellington', 'Christchurch', 'Hamilton', 'Tauranga', 'Napier', 'Dunedin', 'Palmerston North'],
  'Nicaragua': ['Managua', 'León', 'Masaya', 'Matagalpa', 'Granada'],
  'Niger': ['Niamey', 'Zinder', 'Maradi', 'Agadez', 'Tahoua'],
  'Nigeria': ['Lagos', 'Abuja', 'Kano', 'Ibadan', 'Port Harcourt', 'Benin City', 'Kaduna', 'Aba', 'Onitsha', 'Maiduguri'],
  'North Korea': ['Pyongyang', 'Hamhung', 'Chongjin', 'Nampo'],
  'North Macedonia': ['Skopje', 'Bitola', 'Kumanovo', 'Prilep', 'Tetovo'],
  'Norway': ['Oslo', 'Bergen', 'Trondheim', 'Stavanger', 'Drammen', 'Kristiansand'],
  'Oman': ['Muscat', 'Salalah', 'Sohar', 'Nizwa', 'Sur'],
  'Pakistan': ['Karachi', 'Lahore', 'Faisalabad', 'Rawalpindi', 'Islamabad', 'Multan', 'Hyderabad', 'Gujranwala', 'Peshawar', 'Quetta', 'Sialkot', 'Abbottabad', 'Mardan', 'Swat', 'Jhelum', 'Gujrat', 'Sargodha', 'Bahawalpur', 'Sukkur', 'Larkana', 'Rahim Yar Khan', 'Sahiwal', 'Okara', 'Kasur', 'Nowshera', 'Sheikhupura', 'Mandi Bahauddin', 'Khanewal', 'Mianwali', 'Kohat', 'Dera Ghazi Khan', 'Muzzafargarh', 'Vehari', 'Chakwal', 'Murree', 'Haripur', 'Attock', 'Taxila', 'Kotli', 'Mirpur', 'Bhimber'],
  'Palau': ['Ngerulmud', 'Koror', 'Airai'],
  'Palestine': ['Ramallah', 'Gaza City', 'Hebron', 'Nablus', 'Bethlehem', 'Jenin'],
  'Panama': ['Panama City', 'San Miguelito', 'David', 'Colón', 'La Chorrera'],
  'Papua New Guinea': ['Port Moresby', 'Lae', 'Mount Hagen', 'Madang', 'Goroka'],
  'Paraguay': ['Asunción', 'Ciudad del Este', 'San Lorenzo', 'Luque', 'Encarnación'],
  'Peru': ['Lima', 'Arequipa', 'Trujillo', 'Chiclayo', 'Piura', 'Cusco', 'Iquitos'],
  'Philippines': ['Manila', 'Quezon City', 'Davao City', 'Cebu City', 'Caloocan', 'Zamboanga City', 'Taguig', 'Makati', 'Iloilo City'],
  'Poland': ['Warsaw', 'Kraków', 'Łódź', 'Wrocław', 'Poznań', 'Gdańsk', 'Szczecin', 'Bydgoszcz', 'Lublin', 'Katowice'],
  'Portugal': ['Lisbon', 'Porto', 'Braga', 'Coimbra', 'Faro', 'Funchal'],
  'Qatar': ['Doha', 'Al Rayyan', 'Wakra', 'Lusail'],
  'Romania': ['Bucharest', 'Cluj-Napoca', 'Timișoara', 'Iași', 'Constanța', 'Craiova', 'Brașov'],
  'Russia': ['Moscow', 'Saint Petersburg', 'Novosibirsk', 'Yekaterinburg', 'Kazan', 'Nizhny Novgorod', 'Chelyabinsk', 'Samara', 'Omsk', 'Rostov-on-Don', 'Krasnodar', 'Vladivostok'],
  'Rwanda': ['Kigali', 'Butare', 'Gitarama', 'Muhanga'],
  'Saint Kitts and Nevis': ['Basseterre', 'Charlestown', 'Sandy Point Town'],
  'Saint Lucia': ['Castries', 'Vieux Fort', 'Soufrière'],
  'Saint Vincent and the Grenadines': ['Kingstown', 'Georgetown', 'Barrouallie'],
  'Samoa': ['Apia', 'Vaitele', 'Faleula'],
  'San Marino': ['San Marino', 'Serravalle', 'Borgo Maggiore'],
  'Sao Tome and Principe': ['São Tomé', 'Santo António'],
  'Saudi Arabia': ['Riyadh', 'Jeddah', 'Mecca', 'Medina', 'Dammam', 'Khobar', 'Tabuk', 'Abha', 'Yanbu'],
  'Senegal': ['Dakar', 'Touba', 'Thiès', 'Rufisque', 'Saint-Louis', 'Kaolack'],
  'Serbia': ['Belgrade', 'Novi Sad', 'Niš', 'Kragujevac', 'Subotica'],
  'Seychelles': ['Victoria', 'Anse Boileau', 'Beau Vallon'],
  'Sierra Leone': ['Freetown', 'Bo', 'Kenema', 'Makeni'],
  'Singapore': ['Singapore', 'Tampines', 'Woodlands', 'Jurong East'],
  'Slovakia': ['Bratislava', 'Košice', 'Prešov', 'Žilina', 'Nitra'],
  'Slovenia': ['Ljubljana', 'Maribor', 'Celje', 'Kranj', 'Koper'],
  'Solomon Islands': ['Honiara', 'Auki', 'Gizo'],
  'Somalia': ['Mogadishu', 'Hargeisa', 'Bosaso', 'Kismayo', 'Baidoa'],
  'South Africa': ['Johannesburg', 'Cape Town', 'Durban', 'Pretoria', 'Port Elizabeth', 'Bloemfontein', 'East London', 'Polokwane'],
  'South Korea': ['Seoul', 'Busan', 'Incheon', 'Daegu', 'Daejeon', 'Gwangju', 'Suwon', 'Ulsan', 'Seongnam'],
  'South Sudan': ['Juba', 'Wau', 'Malakal', 'Bor'],
  'Spain': ['Madrid', 'Barcelona', 'Valencia', 'Seville', 'Zaragoza', 'Málaga', 'Murcia', 'Bilbao', 'Alicante', 'Granada', 'Palma'],
  'Sri Lanka': ['Colombo', 'Kandy', 'Galle', 'Jaffna', 'Negombo', 'Batticaloa'],
  'Sudan': ['Khartoum', 'Omdurman', 'Kassala', 'Port Sudan', 'El Obeid'],
  'Suriname': ['Paramaribo', 'Lelydorp', 'Nieuw Nickerie'],
  'Sweden': ['Stockholm', 'Gothenburg', 'Malmö', 'Uppsala', 'Västerås', 'Örebro', 'Linköping', 'Helsingborg'],
  'Switzerland': ['Zurich', 'Geneva', 'Basel', 'Lausanne', 'Bern', 'Winterthur', 'Lucerne'],
  'Syria': ['Damascus', 'Aleppo', 'Homs', 'Latakia', 'Hama', 'Deir ez-Zor'],
  'Taiwan': ['Taipei', 'New Taipei', 'Kaohsiung', 'Taichung', 'Tainan', 'Taoyuan', 'Hsinchu'],
  'Tajikistan': ['Dushanbe', 'Khujand', 'Kulob', 'Bokhtar'],
  'Tanzania': ['Dar es Salaam', 'Dodoma', 'Mwanza', 'Arusha', 'Mbeya', 'Morogoro', 'Zanzibar City'],
  'Thailand': ['Bangkok', 'Chiang Mai', 'Phuket', 'Pattaya', 'Hat Yai', 'Khon Kaen', 'Nakhon Ratchasima'],
  'Timor-Leste': ['Dili', 'Maliana', 'Baucau'],
  'Togo': ['Lomé', 'Sokodé', 'Kara', 'Kpalimé'],
  'Tonga': ["Nukuʻalofa", 'Neiafu', 'Haveluloto'],
  'Trinidad and Tobago': ['Port of Spain', 'San Fernando', 'Chaguanas', 'Arima'],
  'Tunisia': ['Tunis', 'Sfax', 'Sousse', 'Kairouan', 'Bizerte', 'Gabès'],
  'Turkey': ['Istanbul', 'Ankara', 'Izmir', 'Bursa', 'Antalya', 'Adana', 'Gaziantep', 'Konya', 'Kayseri'],
  'Turkmenistan': ['Ashgabat', 'Türkmenabat', 'Daşoguz', 'Mary'],
  'Tuvalu': ['Funafuti', 'Nanumaga', 'Niutao'],
  'Uganda': ['Kampala', 'Gulu', 'Mbarara', 'Jinja', 'Mbale'],
  'Ukraine': ['Kyiv', 'Kharkiv', 'Odesa', 'Dnipro', 'Donetsk', 'Zaporizhzhia', 'Lviv', 'Kryvyi Rih', 'Mykolaiv'],
  'United Arab Emirates': ['Dubai', 'Abu Dhabi', 'Sharjah', 'Al Ain', 'Ajman', 'Ras Al Khaimah'],
  'United Kingdom': ['London', 'Birmingham', 'Manchester', 'Glasgow', 'Liverpool', 'Leeds', 'Edinburgh', 'Bristol', 'Sheffield', 'Nottingham', 'Newcastle upon Tyne', 'Cardiff', 'Belfast', 'Leicester', 'Bradford'],
  'United States': [
    'New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix', 'Philadelphia', 'San Antonio',
    'San Diego', 'Dallas', 'San Jose', 'Austin', 'Jacksonville', 'Fort Worth', 'Columbus',
    'Charlotte', 'Indianapolis', 'San Francisco', 'Seattle', 'Denver', 'Washington', 'Boston',
    'Nashville', 'Detroit', 'Oklahoma City', 'Portland', 'Las Vegas', 'Memphis', 'Louisville',
    'Baltimore', 'Milwaukee', 'Albuquerque', 'Tucson', 'Fresno', 'Sacramento', 'Kansas City',
    'Mesa', 'Atlanta', 'Omaha', 'Colorado Springs', 'Raleigh', 'Long Beach', 'Miami', 'Oakland',
    'Minneapolis', 'Tulsa', 'Tampa', 'Arlington', 'Wichita', 'Bakersfield', 'Aurora', 'Honolulu',
    'Cleveland', 'Anaheim', 'Lexington', 'Stockton', 'Corpus Christi', 'Henderson', 'Saint Paul',
    'St. Louis', 'Cincinnati', 'Pittsburgh', 'Greensboro', 'Lincoln', 'Anchorage', 'Plano',
    'Orlando', 'Irvine', 'Newark', 'Durham', 'Toledo', 'Fort Lauderdale', 'St. Petersburg',
    'Jersey City', 'Chandler', 'Scottsdale', 'Garland', 'Madison', 'Norfolk', 'Grand Rapids',
    'Hialeah', 'Virginia Beach', 'New Orleans', 'Oxnard', 'Salt Lake City', 'Worcester',
    'Richmond', 'Boise', 'Birmingham', 'Spokane', 'Rochester', 'Des Moines', 'Montgomery',
    'Modesto', 'Fayetteville', 'Shreveport', 'Akron', 'Tacoma', 'Aurora', 'Fort Wayne',
    'Springfield', 'Laredo', 'Augusta', 'Wilmington', 'Little Rock', 'Knoxville', 'Chattanooga',
    'Hartford', 'Lansing', 'Eugene', 'Savannah', 'Providence', 'Sioux Falls', 'Charleston',
    'Buffalo', 'Huntsville', 'Salem', 'San Bernardino', 'Frisco', 'Tempe', 'Cary', 'Alpharetta',
    'Round Rock', 'Midland', 'Odessa', 'Amarillo', 'Lubbock', 'El Paso', 'McAllen', 'Brownsville',
  ],
  'Uruguay': ['Montevideo', 'Salto', 'Ciudad de la Costa', 'Paysandú', 'Maldonado'],
  'Uzbekistan': ['Tashkent', 'Samarkand', 'Namangan', 'Andijan', 'Bukhara', 'Nukus'],
  'Vanuatu': ['Port Vila', 'Luganville', 'Isangel'],
  'Vatican City': ['Vatican City'],
  'Venezuela': ['Caracas', 'Maracaibo', 'Valencia', 'Barquisimeto', 'Maracay', 'Ciudad Guayana'],
  'Vietnam': ['Ho Chi Minh City', 'Hanoi', 'Da Nang', 'Hai Phong', 'Can Tho', 'Nha Trang', 'Hue', 'Bien Hoa'],
  'Yemen': ["Sana'a", 'Aden', 'Taiz', 'Hodeidah', 'Mukalla'],
  'Zambia': ['Lusaka', 'Kitwe', 'Ndola', 'Kabwe', 'Chingola'],
  'Zimbabwe': ['Harare', 'Bulawayo', 'Chitungwiza', 'Mutare', 'Gweru'],
};

// Returns the city list for a country (canonical COUNTRIES display name).
// Falls back to empty array for unknown countries — the picker still works
// as free text then.
export function citiesForCountry(country: string | null | undefined): string[] {
  if (!country) return [];
  const normalized = country.trim();
  return CITIES_BY_COUNTRY[normalized] || [];
}